name: Check Links 2
run-name: ${{github.actor}} is checking links (exercise 2)
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch
jobs:
  check_links_2:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install broken-link-checker
        run: npm install -g broken-link-checker

      - name: Run link checker
        run: npx broken-link-checker https://learn.madetech.com --exclude microsoft --exclude linkedin --exclude twitter --exclude codewars.com -ro