name: Build Docker Image
on:
  workflow-dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker build
      uses: docker/setup-buildx-action@v2

    - name: Build and tag the Docker image
      run: |
        docker build -t docker-node-app:latest .

    - name: Show Docker image build history
      run: |
        docker history docker-node-app:latest

    - name: Push Docker image to Docker Hub
      run: |
        docker push docker-node-app:latest