name: Build & Publish Docker Image to GHCR

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: ./docker-app

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    # This are permissions for the GITHUB_TOKEN
    permissions:
      contents: read
      packages: write # Allows pushing to GHCR
      attestations: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}/my-app:latest .

      - name: Push Docker image to GHCR
        run: docker push ghcr.io/${{ github.repository }}/my-app:latest

    
    